import gp, corpus
THEMATIC = """
DIVINITY CIRCUMFERENCE FIRFUMFERENFE INSTAR PILGRIM CICADA PRIMALITY MOBIUS SHADOW SHADOWS
AETHEREAL BUFFERS VOID CARNAL OBSCURA FORM ADHERENCE PRESERVATION CONSUMPTION WELCOME WISDOM
TOTIENT PRIME PRIMES SACRED ENCRYPTED TRUTH SELF EMERGE SURFACE TUNNELING KOAN PARABLE
ANEND ANINSTRUCTION KNOWTHIS LIBERPRIMUS LIBER PRIMUS AWARNING SOMEWISDOM THELOSSOFDIVINITY
ENLIGHTENMENT MASTER STUDENT PROFESSOR CONSCIOUSNESS BOOK MESSAGE NUMBERS WORDS DEATH
EXPERIENCE KNOWLEDGE JOURNEY STRUGGLE SUFFERING INNOCENCE ILLUSIONS CERTAINTY REALITY
ULTIMATELY DISCOVER PILGRIMAGE SHAPE OURSELVES REALITIES WITHIN ARRIVE OUTSIDE EMERGENCE
BEING LAW INTELLIGENCE HOLY LIVES COMMAND OWNSELF QUESTION KWESTION IMPOSE NOTHING OTHERS
FOLLOW INSIDE YOURSELF DOGMA REASON BELONG RIGHT LOSE PRIMAL AMASS WEALTH ATTACHED DESTROY
PRESERVE CONSUME LUCK STRONG OBTAIN NEED WORTH BEHAVIOURS BEHAVIORS PRACTICES THREE CAUSE
AN END THE A I WE YOU IT IS OF TO AND FOR ALL THIS THAT
THREETHREEZEROONE ANALOG ADHERE WARNING TRUTHS SEEK DEEPWEB PAGE HASHES DUTY EVERY
PARABLELIKE SHED OWN FIND THEDIVINITYWITHIN
CABAL ILLUMINATI ANONYMOUS ONION TOR GNUPG PGP OUTGUESS STEGANOGRAPHY
FIBONACCI EULER PHI GEMATRIA RUNE RUNES FUTHORC ANGLOSAXON ALPHABET
AUTHORITY FREEDOM MIND BODY SPIRIT SOUL GOD GODS NATURE UNIVERSE INFINITY
"""
def candidates():
    out={}
    for w in THEMATIC.split():
        w=w.strip().upper()
        if not w: continue
        try: out[w]=gp.key_to_idx(w)
        except ValueError: pass
    # every distinct plaintext word from the solved pages, in index space
    for t,c in corpus.WORDS.items():
        if 2<=len(t)<=16:
            out["w:"+gp.to_text(list(t))]=list(t)
    return out
